const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const compression = require('compression');
const morgan = require('morgan');
const { rateLimit } = require('express-rate-limit');
const errorHandler = require('../middlewares/errorMiddleware');
const productRoutes = require('../routes/productRoute');
const authRoutes = require('../routes/authRoute');
const expenseRoutes = require('../routes/expenseRoute');
const saleRoutes = require('../routes/saleRoute');

const app = express();
app.disable('x-powered-by');
app.set('trust proxy', 1);
app.use(helmet());
app.use(compression());
app.use(express.json({ limit: '100kb' }));
app.use(morgan(process.env.NODE_ENV === 'production' ? 'combined' : 'dev'));
const allowed = (process.env.CLIENT_ORIGIN || 'http://localhost:3000').split(',').map(v=>v.trim());
app.use(cors({ origin(origin, cb) { if (!origin || allowed.includes(origin)) return cb(null,true); cb(new Error('Origin not allowed by CORS')); }, credentials:false }));
app.use('/api/auth', rateLimit({ windowMs: 15*60*1000, limit: 30, standardHeaders:'draft-8', legacyHeaders:false, message:{message:'Too many authentication attempts. Please try again later.'} }));
app.use('/api', rateLimit({ windowMs: 60*1000, limit: 300, standardHeaders:'draft-8', legacyHeaders:false }));
app.get('/api/health', (req,res)=>res.json({status:'ok', timestamp:new Date().toISOString()}));
app.use('/api/auth', authRoutes);
app.use('/api/products', productRoutes);
app.use('/api/expenses', expenseRoutes);
app.use('/api/sales', saleRoutes);
app.use((req,res)=>res.status(404).json({success:false,message:'Route not found'}));
app.use(errorHandler);
module.exports = app;
